# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea98b0024c35ad0fbfbe403cf13bc6a203b86d87da58033b24c1b54a07bd3300e3eb2967010463041282c2270bff70fff18d29bece8d2e723f0cf694ceac8c82

test:
  secret_key_base: 1f8cac8a4edf03c40dca9bf7f6444ee1488cdaac39a1be8d633e1d3e17c89ca55752c5d322cac9a0dde54c2aeb766ad6db38eb6a9f053f5c19a0fc0cd24587d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
